# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\E3\大三\大三上\電機工程專題\測試用\圖像化\project_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1041, 736)
        Dialog.setSizeGripEnabled(True)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(300, 470, 321, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(290, 160, 20, 321))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(610, 160, 20, 321))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(300, 150, 321, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_car1 = QtWidgets.QLabel(Dialog)
        self.label_car1.setGeometry(QtCore.QRect(270, 130, 21, 21))
        self.label_car1.setObjectName("label_car1")
        self.label_sensor1 = QtWidgets.QLabel(Dialog)
        self.label_sensor1.setGeometry(QtCore.QRect(570, 320, 21, 21))
        self.label_sensor1.setObjectName("label_sensor1")
        self.label_sensor2 = QtWidgets.QLabel(Dialog)
        self.label_sensor2.setGeometry(QtCore.QRect(570, 400, 21, 21))
        self.label_sensor2.setObjectName("label_sensor2")
        self.label_sensor3 = QtWidgets.QLabel(Dialog)
        self.label_sensor3.setGeometry(QtCore.QRect(320, 390, 21, 21))
        self.label_sensor3.setObjectName("label_sensor3")
        self.label_agg1 = QtWidgets.QLabel(Dialog)
        self.label_agg1.setGeometry(QtCore.QRect(710, 430, 21, 21))
        self.label_agg1.setObjectName("label_agg1")
        self.label_agg2 = QtWidgets.QLabel(Dialog)
        self.label_agg2.setGeometry(QtCore.QRect(200, 400, 21, 21))
        self.label_agg2.setObjectName("label_agg2")
        self.pushButton_start = QtWidgets.QPushButton(Dialog)
        self.pushButton_start.setGeometry(QtCore.QRect(830, 100, 81, 31))
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_initial = QtWidgets.QPushButton(Dialog)
        self.pushButton_initial.setGeometry(QtCore.QRect(830, 40, 81, 31))
        self.pushButton_initial.setObjectName("pushButton_initial")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 600, 71, 21))
        self.label.setObjectName("label")
        self.textBrowser_sensor = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_sensor.setGeometry(QtCore.QRect(120, 540, 391, 151))
        self.textBrowser_sensor.setObjectName("textBrowser_sensor")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(556, 610, 61, 20))
        self.label_2.setObjectName("label_2")
        self.textBrowser_car = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_car.setGeometry(QtCore.QRect(630, 540, 321, 161))
        self.textBrowser_car.setObjectName("textBrowser_car")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(320, 370, 47, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(520, 410, 47, 12))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(520, 310, 47, 12))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(750, 430, 47, 12))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(170, 400, 31, 21))
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_car1.setText(_translate("Dialog", "TextLabel"))
        self.label_sensor1.setText(_translate("Dialog", "TextLabel"))
        self.label_sensor2.setText(_translate("Dialog", "TextLabel"))
        self.label_sensor3.setText(_translate("Dialog", "TextLabel"))
        self.label_agg1.setText(_translate("Dialog", "TextLabel"))
        self.label_agg2.setText(_translate("Dialog", "TextLabel"))
        self.pushButton_start.setText(_translate("Dialog", "start"))
        self.pushButton_initial.setText(_translate("Dialog", "initial"))
        self.label.setText(_translate("Dialog", "sensor資訊"))
        self.label_2.setText(_translate("Dialog", "車子狀態"))
        self.label_3.setText(_translate("Dialog", "sensor3"))
        self.label_4.setText(_translate("Dialog", "sensor1"))
        self.label_5.setText(_translate("Dialog", "sensor2"))
        self.label_6.setText(_translate("Dialog", "agg1"))
        self.label_7.setText(_translate("Dialog", "agg2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

