from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class MainUi(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.init_ui()
    def init_ui(self):
        self.setWindowTitle("test")
        self.resize(997, 696)
        self.line = QtWidgets.QFrame()
        self.line.setGeometry(300, 470, 321, 20)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame()
        self.line_2.setGeometry(290, 160, 20, 321)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame()
        self.line_3.setGeometry(610, 160, 20, 321)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame()
        self.line_4.setGeometry(300, 150, 321, 20)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_car1 = QtWidgets.QLabel()
        self.label_car1.setGeometry(270, 130, 21, 21)
        self.label_car1.setObjectName("label_car1")
        self.label_sensor1 = QtWidgets.QLabel()
        self.label_sensor1.setGeometry(570, 320, 21, 21)
        self.label_sensor1.setObjectName("label_sensor1")
        self.label_sensor2 = QtWidgets.QLabel()
        self.label_sensor2.setGeometry(570, 400, 21, 21)
        self.label_sensor2.setObjectName("label_sensor2")
        self.label_sensor3 = QtWidgets.QLabel()
        self.label_sensor3.setGeometry(320, 390, 21, 21)
        self.label_sensor3.setObjectName("label_sensor3")
        self.label_agg1 = QtWidgets.QLabel()
        self.label_agg1.setGeometry(710, 430, 21, 21)
        self.label_agg1.setObjectName("label_agg1")
        self.label_agg2 = QtWidgets.QLabel()
        self.label_agg2.setGeometry(200, 400, 21, 21)
        self.label_agg2.setObjectName("label_agg2")
        self.pushButton_start = QtWidgets.QPushButton()
        self.pushButton_start.setGeometry(830, 100, 81, 31)
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_initial = QtWidgets.QPushButton()
        self.pushButton_initial.setGeometry(830, 40, 81, 31)
        self.pushButton_initial.setObjectName("pushButton_initial")

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    gui = MainUi()
    gui.show()
    sys.exit(app.exec_())
