# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\E3\大三\大三上\電機工程專題\測試用\圖像化\project_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1041, 736)
        Dialog.setSizeGripEnabled(True)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(170, 400, 541, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(170, 300, 541, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_car1 = QtWidgets.QLabel(Dialog)
        self.label_car1.setGeometry(QtCore.QRect(400, 330, 61, 61))
        self.label_car1.setObjectName("label_car1")
        self.label_sensor1 = QtWidgets.QLabel(Dialog)
        self.label_sensor1.setGeometry(QtCore.QRect(630, 220, 51, 51))
        self.label_sensor1.setObjectName("label_sensor1")
        self.label_sensor2 = QtWidgets.QLabel(Dialog)
        self.label_sensor2.setGeometry(QtCore.QRect(660, 450, 51, 51))
        self.label_sensor2.setObjectName("label_sensor2")
        self.label_sensor3 = QtWidgets.QLabel(Dialog)
        self.label_sensor3.setGeometry(QtCore.QRect(120, 240, 51, 51))
        self.label_sensor3.setObjectName("label_sensor3")
        self.label_agg1 = QtWidgets.QLabel(Dialog)
        self.label_agg1.setGeometry(QtCore.QRect(820, 350, 51, 51))
        self.label_agg1.setObjectName("label_agg1")
        self.label_agg2 = QtWidgets.QLabel(Dialog)
        self.label_agg2.setGeometry(QtCore.QRect(40, 340, 51, 51))
        self.label_agg2.setObjectName("label_agg2")
        self.pushButton_start = QtWidgets.QPushButton(Dialog)
        self.pushButton_start.setGeometry(QtCore.QRect(830, 100, 81, 31))
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_initial = QtWidgets.QPushButton(Dialog)
        self.pushButton_initial.setGeometry(QtCore.QRect(830, 40, 81, 31))
        self.pushButton_initial.setObjectName("pushButton_initial")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 600, 71, 21))
        self.label.setObjectName("label")
        self.textBrowser_sensor = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_sensor.setGeometry(QtCore.QRect(120, 540, 391, 151))
        self.textBrowser_sensor.setObjectName("textBrowser_sensor")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(556, 610, 61, 20))
        self.label_2.setObjectName("label_2")
        self.textBrowser_car = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_car.setGeometry(QtCore.QRect(630, 540, 321, 161))
        self.textBrowser_car.setObjectName("textBrowser_car")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(210, 260, 47, 12))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(710, 240, 47, 12))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(600, 470, 47, 12))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(890, 370, 47, 12))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(100, 340, 51, 51))
        self.label_7.setObjectName("label_7")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(160, 310, 16, 101))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(700, 310, 20, 101))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.pushButton_stop = QtWidgets.QPushButton(Dialog)
        self.pushButton_stop.setGeometry(QtCore.QRect(830, 160, 81, 31))
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(240, 450, 47, 12))
        self.label_8.setObjectName("label_8")
        self.label_sensor4 = QtWidgets.QLabel(Dialog)
        self.label_sensor4.setGeometry(QtCore.QRect(160, 430, 51, 51))
        self.label_sensor4.setObjectName("label_sensor4")
        self.pushButton_heat = QtWidgets.QPushButton(Dialog)
        self.pushButton_heat.setGeometry(QtCore.QRect(60, 40, 101, 41))
        self.pushButton_heat.setObjectName("pushButton_heat")
        self.comboBox_sensor_heat = QtWidgets.QComboBox(Dialog)
        self.comboBox_sensor_heat.setGeometry(QtCore.QRect(170, 50, 80, 22))
        self.comboBox_sensor_heat.setObjectName("comboBox_sensor_heat")
        self.comboBox_sensor_heat.addItem("")
        self.comboBox_sensor_heat.setItemText(0, "")
        self.comboBox_sensor_heat.addItem("")
        self.comboBox_sensor_heat.addItem("")
        self.comboBox_sensor_heat.addItem("")
        self.comboBox_sensor_heat.addItem("")
        self.pushButton_cool = QtWidgets.QPushButton(Dialog)
        self.pushButton_cool.setGeometry(QtCore.QRect(60, 100, 101, 41))
        self.pushButton_cool.setObjectName("pushButton_cool")
        self.comboBox_sensor_cool = QtWidgets.QComboBox(Dialog)
        self.comboBox_sensor_cool.setGeometry(QtCore.QRect(170, 110, 80, 22))
        self.comboBox_sensor_cool.setObjectName("comboBox_sensor_cool")
        self.comboBox_sensor_cool.addItem("")
        self.comboBox_sensor_cool.setItemText(0, "")
        self.comboBox_sensor_cool.addItem("")
        self.comboBox_sensor_cool.addItem("")
        self.comboBox_sensor_cool.addItem("")
        self.comboBox_sensor_cool.addItem("")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_car1.setText(_translate("Dialog", "TextLabel"))
        self.label_sensor1.setText(_translate("Dialog", "TextLabel"))
        self.label_sensor2.setText(_translate("Dialog", "TextLabel"))
        self.label_sensor3.setText(_translate("Dialog", "TextLabel"))
        self.label_agg1.setText(_translate("Dialog", "TextLabel"))
        self.label_agg2.setText(_translate("Dialog", "TextLabel"))
        self.pushButton_start.setText(_translate("Dialog", "start"))
        self.pushButton_initial.setText(_translate("Dialog", "initial"))
        self.label.setText(_translate("Dialog", "sensor資訊"))
        self.label_2.setText(_translate("Dialog", "車子狀態"))
        self.label_3.setText(_translate("Dialog", "sensor3"))
        self.label_4.setText(_translate("Dialog", "sensor1"))
        self.label_5.setText(_translate("Dialog", "sensor2"))
        self.label_6.setText(_translate("Dialog", "agg1"))
        self.label_7.setText(_translate("Dialog", "agg2"))
        self.pushButton_stop.setText(_translate("Dialog", "stop"))
        self.label_8.setText(_translate("Dialog", "sensor4"))
        self.label_sensor4.setText(_translate("Dialog", "TextLabel"))
        self.pushButton_heat.setText(_translate("Dialog", "加熱"))
        self.comboBox_sensor_heat.setItemText(1, _translate("Dialog", "sensor1"))
        self.comboBox_sensor_heat.setItemText(2, _translate("Dialog", "sensor2"))
        self.comboBox_sensor_heat.setItemText(3, _translate("Dialog", "sensor3"))
        self.comboBox_sensor_heat.setItemText(4, _translate("Dialog", "sensor4"))
        self.pushButton_cool.setText(_translate("Dialog", "降溫"))
        self.comboBox_sensor_cool.setItemText(1, _translate("Dialog", "sensor1"))
        self.comboBox_sensor_cool.setItemText(2, _translate("Dialog", "sensor2"))
        self.comboBox_sensor_cool.setItemText(3, _translate("Dialog", "sensor3"))
        self.comboBox_sensor_cool.setItemText(4, _translate("Dialog", "sensor4"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

